CREATE TABLE category(
CAT_ID	INT primary key NOT NULL,
CAT_NAME	VARCHAR(20) NOT NULL)

INSERT INTO category VALUES (1	,	'BOOKS')
INSERT INTO category VALUES (2	,	'GAME')
INSERT INTO category VALUES (3	,	'GROCERIES')
INSERT INTO category VALUES (4	,	'ELECTRONICS')
INSERT INTO category VALUES (5	,	'CLOTHES')